"""Arco Python client -- re-export layer.

Imports everything from arco_engine and arco_ugens so that existing
``from arco import Sine`` keeps working.
"""
from arco_engine import *
from arco_ugens import *

# Wrappers generated by tools/ugen2py.py; the file is optional (gitignored)
# so a fresh checkout works before codegen has been run.
try:
    from arco_generated import *
except ImportError:
    pass
